language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install radon
    - pip install pep8

# command to run tests
script:
    - py.test --cov . --cov-report term-missing
    - pep8 --first optparse.py
after_success:
    - coveralls
    - radon cc src/.
    - radon raw src/.
    - radon mi src/.
    - radon cc tests/.
    - radon raw tests/.
    - radon mi tests/.
