language: python
python:
    - "2.7"

install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install radon
    - pip install pep8

script:
    - py.test --cov . --cov-report term-missing
    - pep8 --first src/.
    - pep8 --first tests/.
    - pep8 --count src/.
    - pep8 --count tests/.

notifications:
  email:
    recipients:
      - miguelbermejotorrent@gmail.com
    on_failure: change # [always|never|change] # default: always


after_success:
    - coveralls
    - radon cc src/.
    - radon raw src/.
    - radon mi src/.
    - radon cc tests/.
    - radon raw tests/.
    - radon mi tests/.

